USE `ww`;
DROP procedure IF EXISTS `operationsInsert`;

DELIMITER $$
USE `ww`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `operationsInsert`(
  sourceId int (11),
  sourceKey varchar (45),
  code varchar (45),
  enabled tinyint (4),
  iconPath varchar (255),
  description varchar (255),
  info varchar (1023),
  flagId int (11),
  typeId int (11),
  isPricePerHour tinyint (4),
  isWorkingHours tinyint (4),
  isWorkWatch tinyint (4),
  isAllTerminals tinyint (4),
  isAskAmounts tinyint (4),
  isAskNextJobTime tinyint (4),
  isAskLocation tinyint (4),
  isMultiUser tinyint (4),
  isMultiMachine tinyint (4),
  nextActionAfter int (11),
  jobOption int (11),
  machineOption int (11),
  userOption int (11),
  subOperationId int (11),
  warningType int (11),
  warningValue double ,
  alarmType int (11),
  alarmValue double ,
  OUT lid int
)
BEGIN
  INSERT INTO operations(	
	sourceId,
	sourceKey,
	code,
	enabled,
	iconPath,
	description,
	info,
	flagId,
	typeId,
	isPricePerHour,
	isWorkingHours,
	isWorkWatch,
	isAllTerminals,
	isAskAmounts,
	isAskNextJobTime,
	isAskLocation,
	isMultiUser,
	isMultiMachine,
	nextActionAfter,
	jobOption,
	machineOption,
	userOption,
	subOperationId,
	warningType,
	warningValue,
	alarmType,
	alarmValue,
	lastModified)
  VALUES(	
	sourceId,
	sourceKey,
	code,
	enabled,
	iconPath,
	description,
	info,
	flagId,
	typeId,
	isPricePerHour,
	isWorkingHours,
	isWorkWatch,
	isAllTerminals,
	isAskAmounts,
	isAskNextJobTime,
	isAskLocation,
	isMultiUser,
	isMultiMachine,
	nextActionAfter,
	jobOption,
	machineOption,
	userOption,
	subOperationId,
	warningType,
	warningValue,
	alarmType,
	alarmValue,
	now());
  SET lid = last_insert_id();
END$$

DELIMITER ;